import { Product } from './interfaces/product.interface';

export const PRODUCTS_MOCK: Product[] = [
  {
    id: 1,
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    description: 'Fragancia fresca y amaderada con notas de cítricos y cedro.',
    price: 85000,
    inStock: true,
    gender: 'man',
    type: 'designer',
  },
  {
    id: 2,
    name: 'Black Orchid',
    brand: 'Tom Ford',
    description: 'Floral oscuro y lujoso con orquídea negra y especias.',
    price: 140000,
    discountPercentage: 15,
    inStock: true,
    gender: 'unisex',
    type: 'niche',
  },
  {
    id: 3,
    name: 'La Nuit de L\'Homme',
    brand: 'Yves Saint Laurent',
    description: 'Oriental especiado con cardamomo, cedro y almizcle.',
    price: 72000,
    inStock: false,
    gender: 'man',
    type: 'designer',
  },
  {
    id: 4,
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    description: 'Amaderado floral con jazmín, azafrán y cedro de Cachemira.',
    price: 320000,
    inStock: true,
    gender: 'unisex',
    type: 'niche',
  },
  {
    id: 5,
    name: 'Oud Ispahan',
    brand: 'Dior',
    description: 'Oud intenso y amaderado con rosa de Damasco.',
    price: 180000,
    discountPercentage: 10,
    inStock: true,
    gender: 'unisex',
    type: 'arabic',
  },
  {
    id: 6,
    name: 'Chance Eau Tendre',
    brand: 'Chanel',
    description: 'Floral frutal con pomelo, jazmín y almizcle blanco.',
    price: 88000,
    inStock: true,
    gender: 'woman',
    type: 'designer',
  },
  {
    id: 7,
    name: 'Rose Oud',
    brand: 'Lattafa',
    description: 'Rosa intensa con oud ahumado, tradicional árabe.',
    price: 45000,
    inStock: false,
    gender: 'woman',
    type: 'arabic',
  },
  {
    id: 8,
    name: 'Aventus',
    brand: 'Creed',
    description: 'Frutal amaderado con piña, abedul y almizcle.',
    price: 410000,
    inStock: true,
    gender: 'man',
    type: 'niche',
  },
];